language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    #- WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    #- WP_VERSION=3.8 WP_MULTISITE=1
    - WP_VERSION=3.5 WP_MULTISITE=0
    #- WP_VERSION=3.5 WP_MULTISITE=1

before_script:
    - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

branches:
    only:
        - master
        - alpha

notifications:
    notifications:
        hipchat:
            rooms:
                - secure: "P7ChqZStvixQt6nZBV4H2k1QyC/WFz4lh/fp6Fjb8TtgiDHVGP7B0+srh1tSReCrswrR9dELmCk83HOieEp+6y1Kf1VhJ5SxivTHdcGcWsatLDIP0/HfjrzsRTIaX1Yxk7oXNvkwdJx74AJrv7bWdY6IYjysHBMWEqhDnjeq7o8="
            template:
                - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"
